export type JqFlag = "-r" | "-c" | "-s" | "-n" | "-S"

export interface JqExample {
  id: string
  title: string
  description: string
  filter: string
  input: string
  flags: JqFlag[]
  /** Output of jq 1.8.2 for the filter and input above (compact, except pretty-print-json) */
  output: string
}

export interface JqExampleCategory {
  id: string
  title: string
  description: string
  examples: JqExample[]
}

export const jqExampleCategories: JqExampleCategory[] = [
  {
    id: "basics",
    title: "Basics",
    description: "Access fields, arrays and nested values.",
    examples: [
      {
        id: "pretty-print-json",
        title: "Pretty-print JSON",
        description: "The identity filter `.` returns the input unchanged, formatted and indented.",
        filter: ".",
        input: "{\"name\":\"Alice\",\"tags\":[\"admin\",\"dev\"],\"active\":true}",
        flags: [],
        output: "{\n  \"name\": \"Alice\",\n  \"tags\": [\n    \"admin\",\n    \"dev\"\n  ],\n  \"active\": true\n}",
      },
      {
        id: "get-field",
        title: "Get a field from an object",
        description: "Use `.key` to read a single field. Missing keys return `null` instead of failing.",
        filter: ".name",
        input: "{\"name\": \"Alice\", \"email\": \"alice@example.com\"}",
        flags: [],
        output: "\"Alice\"",
      },
      {
        id: "nested-field",
        title: "Read a nested field",
        description: "Chain keys to walk into nested objects.",
        filter: ".user.address.city",
        input: "{\"user\": {\"address\": {\"city\": \"Lugano\", \"zip\": \"6900\"}}}",
        flags: [],
        output: "\"Lugano\"",
      },
      {
        id: "array-index-slice",
        title: "Array index and slice",
        description: "`.[0]` is the first element, `.[-1]` the last, `.[1:3]` a slice.",
        filter: "[.[0], .[-1], .[1:3]]",
        input: "[\"a\", \"b\", \"c\", \"d\"]",
        flags: [],
        output: "[\"a\",\"d\",[\"b\",\"c\"]]",
      },
      {
        id: "iterate-array",
        title: "Iterate over an array",
        description: "`.[]` emits every element; pipe each one into the next filter.",
        filter: ".users[].name",
        input: "{\"users\": [{\"name\": \"Alice\"}, {\"name\": \"Bob\"}]}",
        flags: [],
        output: "\"Alice\"\n\"Bob\"",
      },
      {
        id: "keys-and-length",
        title: "List keys and count items",
        description: "`keys` returns sorted object keys; `length` counts elements, keys or characters.",
        filter: "{keys: keys, count: length}",
        input: "{\"b\": 2, \"a\": 1, \"c\": 3}",
        flags: [],
        output: "{\"keys\":[\"a\",\"b\",\"c\"],\"count\":3}",
      },
    ],
  },
  {
    id: "filter",
    title: "Filter and select",
    description: "Keep only the values you need.",
    examples: [
      {
        id: "select-by-condition",
        title: "Filter an array with select",
        description: "`select(cond)` keeps the values for which the condition is true.",
        filter: "map(select(.active) | .name)",
        input: "[{\"name\": \"Alice\", \"age\": 34, \"active\": true, \"dept\": \"eng\"}, {\"name\": \"Bob\", \"age\": 27, \"active\": false, \"dept\": \"ops\"}, {\"name\": \"Carol\", \"age\": 41, \"active\": true, \"dept\": \"eng\"}]",
        flags: [],
        output: "[\"Alice\",\"Carol\"]",
      },
      {
        id: "select-by-comparison",
        title: "Select objects by a numeric field",
        description: "Combine `select` with comparison operators.",
        filter: ".[] | select(.age > 30) | .name",
        input: "[{\"name\": \"Alice\", \"age\": 34, \"active\": true, \"dept\": \"eng\"}, {\"name\": \"Bob\", \"age\": 27, \"active\": false, \"dept\": \"ops\"}, {\"name\": \"Carol\", \"age\": 41, \"active\": true, \"dept\": \"eng\"}]",
        flags: [],
        output: "\"Alice\"\n\"Carol\"",
      },
      {
        id: "select-by-regex",
        title: "Match strings with a regex",
        description: "`test(regex)` returns true when the string matches.",
        filter: "map(select(.email | test(\"@example\\\\.com$\")))",
        input: "[{\"email\": \"alice@example.com\"}, {\"email\": \"bob@test.org\"}]",
        flags: [],
        output: "[{\"email\":\"alice@example.com\"}]",
      },
      {
        id: "select-contains",
        title: "Check whether an array contains a value",
        description: "`index(value)` or `any(...)` find a value inside an array.",
        filter: "map(select(any(.tags[]; . == \"jq\")) | .name)",
        input: "[{\"name\": \"a\", \"tags\": [\"jq\", \"json\"]}, {\"name\": \"b\", \"tags\": [\"yaml\"]}]",
        flags: [],
        output: "[\"a\"]",
      },
      {
        id: "has-key",
        title: "Check if a key exists",
        description: "`has(key)` tests for a key, even when its value is null.",
        filter: "map(has(\"email\"))",
        input: "[{\"email\": null}, {\"name\": \"Bob\"}]",
        flags: [],
        output: "[true,false]",
      },
      {
        id: "first-match",
        title: "Get the first match only",
        description: "`first(expr)` stops after the first output.",
        filter: "first(.[] | select(.age > 30)) | .name",
        input: "[{\"name\": \"Alice\", \"age\": 34, \"active\": true, \"dept\": \"eng\"}, {\"name\": \"Bob\", \"age\": 27, \"active\": false, \"dept\": \"ops\"}, {\"name\": \"Carol\", \"age\": 41, \"active\": true, \"dept\": \"eng\"}]",
        flags: [],
        output: "\"Alice\"",
      },
    ],
  },
  {
    id: "transform",
    title: "Transform",
    description: "Reshape objects and arrays.",
    examples: [
      {
        id: "map-array",
        title: "Transform every element with map",
        description: "`map(f)` applies a filter to each array element.",
        filter: "map(.price * .qty)",
        input: "[{\"price\": 3, \"qty\": 2}, {\"price\": 10, \"qty\": 1}]",
        flags: [],
        output: "[6,10]",
      },
      {
        id: "build-object",
        title: "Build a new object",
        description: "Use `{}` to pick and rename fields.",
        filter: "map({user: .name, isAdult: (.age >= 18)})",
        input: "[{\"name\": \"Alice\", \"age\": 34}, {\"name\": \"Tim\", \"age\": 12}]",
        flags: [],
        output: "[{\"user\":\"Alice\",\"isAdult\":true},{\"user\":\"Tim\",\"isAdult\":false}]",
      },
      {
        id: "delete-key",
        title: "Delete a key",
        description: "`del(path)` removes fields, e.g. secrets before sharing a payload.",
        filter: "del(.password, .token)",
        input: "{\"user\": \"alice\", \"password\": \"s3cret\", \"token\": \"abc\"}",
        flags: [],
        output: "{\"user\":\"alice\"}",
      },
      {
        id: "update-in-place",
        title: "Update values in place",
        description: "`|=` updates the value at a path and keeps the rest of the document.",
        filter: ".items[].price |= . * 2",
        input: "{\"items\": [{\"id\": 1, \"price\": 5}, {\"id\": 2, \"price\": 8}]}",
        flags: [],
        output: "{\"items\":[{\"id\":1,\"price\":10},{\"id\":2,\"price\":16}]}",
      },
      {
        id: "rename-keys",
        title: "Rename all keys with with_entries",
        description: "`with_entries` lets you rewrite keys and values of an object.",
        filter: "with_entries(.key |= ascii_upcase)",
        input: "{\"host\": \"localhost\", \"port\": 8080}",
        flags: [],
        output: "{\"HOST\":\"localhost\",\"PORT\":8080}",
      },
      {
        id: "default-value",
        title: "Provide a default value",
        description: "The alternative operator `//` replaces `null` or `false` with a fallback.",
        filter: "map(.nickname // \"anonymous\")",
        input: "[{\"nickname\": \"ally\"}, {\"name\": \"Bob\"}]",
        flags: [],
        output: "[\"ally\",\"anonymous\"]",
      },
      {
        id: "if-then-else",
        title: "Conditional values with if-then-else",
        description: "jq has full `if ... then ... elif ... else ... end` expressions.",
        filter: "map(if .score >= 60 then \"pass\" else \"fail\" end)",
        input: "[{\"score\": 72}, {\"score\": 45}]",
        flags: [],
        output: "[\"pass\",\"fail\"]",
      },
      {
        id: "merge-objects",
        title: "Merge objects",
        description: "`*` deep-merges two objects; `add` merges an array of objects.",
        filter: ".defaults * .overrides",
        input: "{\"defaults\": {\"debug\": false, \"db\": {\"host\": \"localhost\", \"port\": 5432}}, \"overrides\": {\"db\": {\"host\": \"db.internal\"}}}",
        flags: [],
        output: "{\"debug\":false,\"db\":{\"host\":\"db.internal\",\"port\":5432}}",
      },
    ],
  },
  {
    id: "aggregate",
    title: "Sort, group and aggregate",
    description: "Summaries and reports from arrays of objects.",
    examples: [
      {
        id: "sort-by-field",
        title: "Sort an array of objects by a field",
        description: "`sort_by(f)` sorts ascending; add `reverse` for descending order.",
        filter: "sort_by(.age) | reverse | map(.name)",
        input: "[{\"name\": \"Alice\", \"age\": 34, \"active\": true, \"dept\": \"eng\"}, {\"name\": \"Bob\", \"age\": 27, \"active\": false, \"dept\": \"ops\"}, {\"name\": \"Carol\", \"age\": 41, \"active\": true, \"dept\": \"eng\"}]",
        flags: [],
        output: "[\"Carol\",\"Alice\",\"Bob\"]",
      },
      {
        id: "group-and-count",
        title: "Group by a field and count",
        description: "`group_by(f)` groups equal values; build one summary object per group.",
        filter: "group_by(.dept) | map({dept: .[0].dept, count: length})",
        input: "[{\"name\": \"Alice\", \"age\": 34, \"active\": true, \"dept\": \"eng\"}, {\"name\": \"Bob\", \"age\": 27, \"active\": false, \"dept\": \"ops\"}, {\"name\": \"Carol\", \"age\": 41, \"active\": true, \"dept\": \"eng\"}]",
        flags: [],
        output: "[{\"dept\":\"eng\",\"count\":2},{\"dept\":\"ops\",\"count\":1}]",
      },
      {
        id: "sum-values",
        title: "Sum values",
        description: "`add` sums numbers (and concatenates strings or arrays).",
        filter: "map(.amount) | add",
        input: "[{\"amount\": 12.5}, {\"amount\": 7.5}, {\"amount\": 30}]",
        flags: [],
        output: "50",
      },
      {
        id: "unique-values",
        title: "Unique values",
        description: "`unique` sorts and removes duplicates; `unique_by(f)` dedupes by a key.",
        filter: "map(.tag) | unique",
        input: "[{\"tag\": \"b\"}, {\"tag\": \"a\"}, {\"tag\": \"b\"}]",
        flags: [],
        output: "[\"a\",\"b\"]",
      },
      {
        id: "min-max-by",
        title: "Find min and max by a field",
        description: "`min_by(f)` and `max_by(f)` return the whole matching object.",
        filter: "{cheapest: min_by(.price).name, priciest: max_by(.price).name}",
        input: "[{\"name\": \"pen\", \"price\": 2}, {\"name\": \"book\", \"price\": 15}, {\"name\": \"mug\", \"price\": 8}]",
        flags: [],
        output: "{\"cheapest\":\"pen\",\"priciest\":\"book\"}",
      },
      {
        id: "reduce-to-object",
        title: "Build a lookup table with reduce",
        description: "`reduce` folds an array into a single value, here an id-to-name map.",
        filter: "reduce .[] as $u ({}; .[$u.id] = $u.name)",
        input: "[{\"id\": \"u1\", \"name\": \"Alice\"}, {\"id\": \"u2\", \"name\": \"Bob\"}]",
        flags: [],
        output: "{\"u1\":\"Alice\",\"u2\":\"Bob\"}",
      },
    ],
  },
  {
    id: "strings",
    title: "Strings and output formats",
    description: "Text, CSV, Base64 and raw output.",
    examples: [
      {
        id: "string-interpolation",
        title: "String interpolation",
        description: "Embed expressions in strings with `\\(...)`.",
        filter: ".[] | \"\\(.name) is \\(.age) years old\"",
        input: "[{\"name\": \"Alice\", \"age\": 34}, {\"name\": \"Bob\", \"age\": 27}]",
        flags: ["-r"],
        output: "Alice is 34 years old\nBob is 27 years old",
      },
      {
        id: "split-join",
        title: "Split and join strings",
        description: "`split(sep)` and `join(sep)` convert between strings and arrays.",
        filter: ".path | split(\"/\") | map(select(. != \"\")) | join(\" > \")",
        input: "{\"path\": \"/usr/local/bin\"}",
        flags: [],
        output: "\"usr > local > bin\"",
      },
      {
        id: "to-csv",
        title: "Convert JSON to CSV",
        description: "Build an array per row and format it with `@csv`; use raw output (-r).",
        filter: "[\"name\", \"age\"], (.[] | [.name, .age]) | @csv",
        input: "[{\"name\": \"Alice\", \"age\": 34}, {\"name\": \"Bob\", \"age\": 27}]",
        flags: ["-r"],
        output: "\"name\",\"age\"\n\"Alice\",34\n\"Bob\",27",
      },
      {
        id: "env-file",
        title: "Turn an object into KEY=value lines",
        description: "`to_entries` exposes key/value pairs, handy for .env files.",
        filter: "to_entries[] | \"\\(.key)=\\(.value)\"",
        input: "{\"HOST\": \"localhost\", \"PORT\": 8080}",
        flags: ["-r"],
        output: "HOST=localhost\nPORT=8080",
      },
      {
        id: "base64",
        title: "Encode and decode Base64",
        description: "`@base64` encodes a string, `@base64d` decodes it.",
        filter: "{encoded: (.text | @base64), decoded: (.b64 | @base64d)}",
        input: "{\"text\": \"hello jq\", \"b64\": \"anNvbg==\"}",
        flags: [],
        output: "{\"encoded\":\"aGVsbG8ganE=\",\"decoded\":\"json\"}",
      },
      {
        id: "parse-embedded-json",
        title: "Parse a JSON string inside JSON",
        description: "`fromjson` parses an escaped JSON string; `tojson` does the opposite.",
        filter: ".payload | fromjson | .id",
        input: "{\"payload\": \"{\\\"id\\\": 42, \\\"ok\\\": true}\"}",
        flags: [],
        output: "42",
      },
      {
        id: "unix-timestamp",
        title: "Convert a Unix timestamp to a date",
        description: "`todate` formats seconds since epoch as ISO 8601; `strftime` gives custom formats.",
        filter: ".created | {iso: todate, day: strftime(\"%Y-%m-%d\")}",
        input: "{\"created\": 1700000000}",
        flags: [],
        output: "{\"iso\":\"2023-11-14T22:13:20Z\",\"day\":\"2023-11-14\"}",
      },
    ],
  },
  {
    id: "advanced",
    title: "Advanced",
    description: "Recursion, paths and multiple inputs.",
    examples: [
      {
        id: "recursive-search",
        title: "Find a key at any depth",
        description: "`..` walks every value recursively; `.id? // empty` keeps only ids.",
        filter: "[.. | .id? // empty]",
        input: "{\"id\": 1, \"children\": [{\"id\": 2, \"children\": [{\"id\": 3}]}]}",
        flags: [],
        output: "[1,2,3]",
      },
      {
        id: "list-paths",
        title: "List all leaf paths",
        description: "`paths(f)` returns the path to every value matching `f`; `scalars` matches leaves (but skips `false` and `null`).",
        filter: "[paths(scalars) | map(tostring) | join(\".\")]",
        input: "{\"a\": {\"b\": 1, \"c\": [\"x\", \"y\"]}}",
        flags: [],
        output: "[\"a.b\",\"a.c.0\",\"a.c.1\"]",
      },
      {
        id: "flatten",
        title: "Flatten nested arrays",
        description: "`flatten` removes nesting; pass a depth to flatten only some levels.",
        filter: "flatten",
        input: "[1, [2, [3, [4]]]]",
        flags: [],
        output: "[1,2,3,4]",
      },
      {
        id: "slurp-inputs",
        title: "Combine multiple JSON documents (slurp)",
        description: "With `-s` jq reads all inputs into one array, e.g. for NDJSON logs.",
        filter: "map(.ms) | add / length",
        input: "{\"ms\": 120}\n{\"ms\": 80}\n{\"ms\": 100}",
        flags: ["-s"],
        output: "100",
      },
      {
        id: "null-input",
        title: "Generate JSON without input",
        description: "With `-n` jq ignores input; useful for building JSON from scratch.",
        filter: "[range(1; 4) | {id: ., label: \"item-\\(.)\"}]",
        input: "",
        flags: ["-n"],
        output: "[{\"id\":1,\"label\":\"item-1\"},{\"id\":2,\"label\":\"item-2\"},{\"id\":3,\"label\":\"item-3\"}]",
      },
    ],
  },
]

export const jqExamples: JqExample[] = jqExampleCategories.flatMap((c) => c.examples)

export function findJqExample(id: string): JqExample | undefined {
  return jqExamples.find((e) => e.id === id)
}
